/* Generated by wayland-scanner 1.24.0 */

/*
 * SPDX-FileCopyrightText: © 2025 Isaac Freund
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface river_seat_v1_interface;
extern const struct wl_interface river_xkb_binding_v1_interface;
extern const struct wl_interface river_xkb_bindings_seat_v1_interface;

static const struct wl_interface *river_xkb_bindings_v1_types[] = {
	NULL,
	&river_seat_v1_interface,
	&river_xkb_binding_v1_interface,
	NULL,
	NULL,
	&river_xkb_bindings_seat_v1_interface,
	&river_seat_v1_interface,
};

static const struct wl_message river_xkb_bindings_v1_requests[] = {
	{ "destroy", "", river_xkb_bindings_v1_types + 0 },
	{ "get_xkb_binding", "onuu", river_xkb_bindings_v1_types + 1 },
	{ "get_seat", "2no", river_xkb_bindings_v1_types + 5 },
};

WL_PRIVATE const struct wl_interface river_xkb_bindings_v1_interface = {
	"river_xkb_bindings_v1", 2,
	3, river_xkb_bindings_v1_requests,
	0, NULL,
};

static const struct wl_message river_xkb_binding_v1_requests[] = {
	{ "destroy", "", river_xkb_bindings_v1_types + 0 },
	{ "set_layout_override", "u", river_xkb_bindings_v1_types + 0 },
	{ "enable", "", river_xkb_bindings_v1_types + 0 },
	{ "disable", "", river_xkb_bindings_v1_types + 0 },
};

static const struct wl_message river_xkb_binding_v1_events[] = {
	{ "pressed", "", river_xkb_bindings_v1_types + 0 },
	{ "released", "", river_xkb_bindings_v1_types + 0 },
	{ "stop_repeat", "2", river_xkb_bindings_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_xkb_binding_v1_interface = {
	"river_xkb_binding_v1", 2,
	4, river_xkb_binding_v1_requests,
	3, river_xkb_binding_v1_events,
};

static const struct wl_message river_xkb_bindings_seat_v1_requests[] = {
	{ "destroy", "2", river_xkb_bindings_v1_types + 0 },
	{ "ensure_next_key_eaten", "2", river_xkb_bindings_v1_types + 0 },
	{ "cancel_ensure_next_key_eaten", "2", river_xkb_bindings_v1_types + 0 },
};

static const struct wl_message river_xkb_bindings_seat_v1_events[] = {
	{ "ate_unbound_key", "2", river_xkb_bindings_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_xkb_bindings_seat_v1_interface = {
	"river_xkb_bindings_seat_v1", 2,
	3, river_xkb_bindings_seat_v1_requests,
	1, river_xkb_bindings_seat_v1_events,
};

