/* Generated by wayland-scanner 1.24.0 */

/*
 * SPDX-FileCopyrightText: © 2024 Isaac Freund
 * SPDX-License-Identifier: MIT
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface river_decoration_v1_interface;
extern const struct wl_interface river_node_v1_interface;
extern const struct wl_interface river_output_v1_interface;
extern const struct wl_interface river_pointer_binding_v1_interface;
extern const struct wl_interface river_seat_v1_interface;
extern const struct wl_interface river_shell_surface_v1_interface;
extern const struct wl_interface river_window_v1_interface;
extern const struct wl_interface wl_surface_interface;

static const struct wl_interface *river_window_management_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&river_shell_surface_v1_interface,
	&wl_surface_interface,
	&river_window_v1_interface,
	&river_output_v1_interface,
	&river_seat_v1_interface,
	&river_node_v1_interface,
	&river_decoration_v1_interface,
	&wl_surface_interface,
	&river_decoration_v1_interface,
	&wl_surface_interface,
	&river_output_v1_interface,
	&river_window_v1_interface,
	&river_seat_v1_interface,
	&river_seat_v1_interface,
	NULL,
	&river_output_v1_interface,
	&river_node_v1_interface,
	&river_node_v1_interface,
	&river_node_v1_interface,
	&river_window_v1_interface,
	&river_shell_surface_v1_interface,
	&river_pointer_binding_v1_interface,
	NULL,
	NULL,
	&river_window_v1_interface,
	&river_window_v1_interface,
	&river_shell_surface_v1_interface,
};

static const struct wl_message river_window_manager_v1_requests[] = {
	{ "stop", "", river_window_management_v1_types + 0 },
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "manage_finish", "", river_window_management_v1_types + 0 },
	{ "manage_dirty", "", river_window_management_v1_types + 0 },
	{ "render_finish", "", river_window_management_v1_types + 0 },
	{ "get_shell_surface", "no", river_window_management_v1_types + 6 },
	{ "exit_session", "4", river_window_management_v1_types + 0 },
};

static const struct wl_message river_window_manager_v1_events[] = {
	{ "unavailable", "", river_window_management_v1_types + 0 },
	{ "finished", "", river_window_management_v1_types + 0 },
	{ "manage_start", "", river_window_management_v1_types + 0 },
	{ "render_start", "", river_window_management_v1_types + 0 },
	{ "session_locked", "", river_window_management_v1_types + 0 },
	{ "session_unlocked", "", river_window_management_v1_types + 0 },
	{ "window", "n", river_window_management_v1_types + 8 },
	{ "output", "n", river_window_management_v1_types + 9 },
	{ "seat", "n", river_window_management_v1_types + 10 },
};

WL_PRIVATE const struct wl_interface river_window_manager_v1_interface = {
	"river_window_manager_v1", 4,
	7, river_window_manager_v1_requests,
	9, river_window_manager_v1_events,
};

static const struct wl_message river_window_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "close", "", river_window_management_v1_types + 0 },
	{ "get_node", "n", river_window_management_v1_types + 11 },
	{ "propose_dimensions", "ii", river_window_management_v1_types + 0 },
	{ "hide", "", river_window_management_v1_types + 0 },
	{ "show", "", river_window_management_v1_types + 0 },
	{ "use_csd", "", river_window_management_v1_types + 0 },
	{ "use_ssd", "", river_window_management_v1_types + 0 },
	{ "set_borders", "uiuuuu", river_window_management_v1_types + 0 },
	{ "set_tiled", "u", river_window_management_v1_types + 0 },
	{ "get_decoration_above", "no", river_window_management_v1_types + 12 },
	{ "get_decoration_below", "no", river_window_management_v1_types + 14 },
	{ "inform_resize_start", "", river_window_management_v1_types + 0 },
	{ "inform_resize_end", "", river_window_management_v1_types + 0 },
	{ "set_capabilities", "u", river_window_management_v1_types + 0 },
	{ "inform_maximized", "", river_window_management_v1_types + 0 },
	{ "inform_unmaximized", "", river_window_management_v1_types + 0 },
	{ "inform_fullscreen", "", river_window_management_v1_types + 0 },
	{ "inform_not_fullscreen", "", river_window_management_v1_types + 0 },
	{ "fullscreen", "o", river_window_management_v1_types + 16 },
	{ "exit_fullscreen", "", river_window_management_v1_types + 0 },
	{ "set_clip_box", "2iiii", river_window_management_v1_types + 0 },
	{ "set_content_clip_box", "3iiii", river_window_management_v1_types + 0 },
	{ "set_dimension_bounds", "4ii", river_window_management_v1_types + 0 },
};

static const struct wl_message river_window_v1_events[] = {
	{ "closed", "", river_window_management_v1_types + 0 },
	{ "dimensions_hint", "iiii", river_window_management_v1_types + 0 },
	{ "dimensions", "ii", river_window_management_v1_types + 0 },
	{ "app_id", "?s", river_window_management_v1_types + 0 },
	{ "title", "?s", river_window_management_v1_types + 0 },
	{ "parent", "?o", river_window_management_v1_types + 17 },
	{ "decoration_hint", "u", river_window_management_v1_types + 0 },
	{ "pointer_move_requested", "o", river_window_management_v1_types + 18 },
	{ "pointer_resize_requested", "ou", river_window_management_v1_types + 19 },
	{ "show_window_menu_requested", "ii", river_window_management_v1_types + 0 },
	{ "maximize_requested", "", river_window_management_v1_types + 0 },
	{ "unmaximize_requested", "", river_window_management_v1_types + 0 },
	{ "fullscreen_requested", "?o", river_window_management_v1_types + 21 },
	{ "exit_fullscreen_requested", "", river_window_management_v1_types + 0 },
	{ "minimize_requested", "", river_window_management_v1_types + 0 },
	{ "unreliable_pid", "2i", river_window_management_v1_types + 0 },
	{ "presentation_hint", "4u", river_window_management_v1_types + 0 },
	{ "identifier", "4s", river_window_management_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_window_v1_interface = {
	"river_window_v1", 4,
	24, river_window_v1_requests,
	18, river_window_v1_events,
};

static const struct wl_message river_decoration_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "set_offset", "ii", river_window_management_v1_types + 0 },
	{ "sync_next_commit", "", river_window_management_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_decoration_v1_interface = {
	"river_decoration_v1", 4,
	3, river_decoration_v1_requests,
	0, NULL,
};

static const struct wl_message river_shell_surface_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "get_node", "n", river_window_management_v1_types + 22 },
	{ "sync_next_commit", "", river_window_management_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_shell_surface_v1_interface = {
	"river_shell_surface_v1", 4,
	3, river_shell_surface_v1_requests,
	0, NULL,
};

static const struct wl_message river_node_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "set_position", "ii", river_window_management_v1_types + 0 },
	{ "place_top", "", river_window_management_v1_types + 0 },
	{ "place_bottom", "", river_window_management_v1_types + 0 },
	{ "place_above", "o", river_window_management_v1_types + 23 },
	{ "place_below", "o", river_window_management_v1_types + 24 },
};

WL_PRIVATE const struct wl_interface river_node_v1_interface = {
	"river_node_v1", 4,
	6, river_node_v1_requests,
	0, NULL,
};

static const struct wl_message river_output_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "set_presentation_mode", "4u", river_window_management_v1_types + 0 },
};

static const struct wl_message river_output_v1_events[] = {
	{ "removed", "", river_window_management_v1_types + 0 },
	{ "wl_output", "u", river_window_management_v1_types + 0 },
	{ "position", "ii", river_window_management_v1_types + 0 },
	{ "dimensions", "ii", river_window_management_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_output_v1_interface = {
	"river_output_v1", 4,
	2, river_output_v1_requests,
	4, river_output_v1_events,
};

static const struct wl_message river_seat_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "focus_window", "o", river_window_management_v1_types + 25 },
	{ "focus_shell_surface", "o", river_window_management_v1_types + 26 },
	{ "clear_focus", "", river_window_management_v1_types + 0 },
	{ "op_start_pointer", "", river_window_management_v1_types + 0 },
	{ "op_end", "", river_window_management_v1_types + 0 },
	{ "get_pointer_binding", "nuu", river_window_management_v1_types + 27 },
	{ "set_xcursor_theme", "2su", river_window_management_v1_types + 0 },
	{ "pointer_warp", "3ii", river_window_management_v1_types + 0 },
};

static const struct wl_message river_seat_v1_events[] = {
	{ "removed", "", river_window_management_v1_types + 0 },
	{ "wl_seat", "u", river_window_management_v1_types + 0 },
	{ "pointer_enter", "o", river_window_management_v1_types + 30 },
	{ "pointer_leave", "", river_window_management_v1_types + 0 },
	{ "window_interaction", "o", river_window_management_v1_types + 31 },
	{ "shell_surface_interaction", "o", river_window_management_v1_types + 32 },
	{ "op_delta", "ii", river_window_management_v1_types + 0 },
	{ "op_release", "", river_window_management_v1_types + 0 },
	{ "pointer_position", "2ii", river_window_management_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_seat_v1_interface = {
	"river_seat_v1", 4,
	9, river_seat_v1_requests,
	9, river_seat_v1_events,
};

static const struct wl_message river_pointer_binding_v1_requests[] = {
	{ "destroy", "", river_window_management_v1_types + 0 },
	{ "enable", "", river_window_management_v1_types + 0 },
	{ "disable", "", river_window_management_v1_types + 0 },
};

static const struct wl_message river_pointer_binding_v1_events[] = {
	{ "pressed", "", river_window_management_v1_types + 0 },
	{ "released", "", river_window_management_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface river_pointer_binding_v1_interface = {
	"river_pointer_binding_v1", 4,
	3, river_pointer_binding_v1_requests,
	2, river_pointer_binding_v1_events,
};

